-- Do Not Edit This File.
-- [32] = default; [33] = line number; [34] = brace highlight; [35] = unmatched brace
return {
	common = {
		style = {
			caret = {
				back = "#3a3a3a"
			},
			comment = {
				fore = "#92ff2c",
				italic = true
			},
			deadcode = {
				back = "#101010"
			},
			["doc-comment"] = {
				fore = "#993300",
				italic = true
			},
			["doc-keyword"] = {
				bold = true,
				fore = "#663300",
				italic = true
			},
			["double-quoted-string"] = {
				fore = "#41aa11"
			},
			error = {
				back = "#ff0000",
				eolfilled = true,
				fore = "#ffff00"
			},
			find = {
				back = "#00f3f3"
			},
			["fold-margin"] = {
				back = "#262626"
			},
			identifier = {

			},
			inactive = {
				back = "#450505",
				eolfilled = true
			},
			keyword = {
				bold = true,
				fore = "#ff007f"
			},
			label = {
				fore = "#800000"
			},
			number = {
				fore = "#00d0ff"
			},
			operator = {
				bold = true
			},
			preprocessor = {
				bold = true,
				fore = "#dbc900"
			},
			ref = {
				back = "#74f000"
			},
			selection = {
				back = "#4d4d4d",
				eolfilled = true
			},
			["single-quoted-string"] = {
				fore = "#00cc66"
			},
			["unclosed-double-quoted-string"] = {
				back = "#800000",
				eolfilled = true
			},
			["unclosed-single-quoted-string"] = {
				back = "#800000",
				eolfilled = true
			},
			whitespace = {
				fore = "#808080"
			}
		}
	},
	style = {
		[32] = {
			back = "#1d1d1d",
			fore = "#dcdcdc"
		},
		[33] = {
			back = "#333333",
			fore = "#cccccc"
		},
		[34] = {
			back = "#006100",
			bold = true,
			fore = "#bababa"
		},
		[35] = {
			back = "#8a0000",
			bold = true,
			fore = "#bababa"
		}
	},
	udb = {
		style = {
			ada = {
				["global-variable"] = {
					bold = true,
					fore = "#00a9c3"
				},
				["local-variable"] = {
					fore = "#00a9c3",
					italic = true
				},
				package = {
					fore = "#ff5500"
				},
				subprogram = {
					fore = "#ffaa00"
				},
				type = {
					underline = true
				}
			},
			cs = {
				class = {
					underline = true
				},
				enumerator = {
					fore = "#006dff"
				},
				method = {
					fore = "#ffaa00"
				},
				type = {
					underline = true
				}
			},
			cxx = {
				class = {
					underline = true
				},
				enumerator = {
					fore = "#006dff"
				},
				["function"] = {
					fore = "#fc4120"
				},
				["global-variable"] = {
					bold = true,
					fore = "#00a9c3"
				},
				["local-variable"] = {
					fore = "#00a9c3"
				},
				macro = {
					bold = true,
					fore = "#008000"
				},
				["member-function"] = {
					fore = "#fc4120",
					italic = true
				},
				["member-variable"] = {
					fore = "#00a9c3",
					italic = true
				},
				parameter = {
					fore = "#00c3ac"
				},
				type = {
					underline = true
				},
				["virtual-function"] = {
					bold = true,
					fore = "#fc4120",
					italic = true
				}
			},
			fortran = {
				subprogram = {
					fore = "#ffaa00"
				},
				type = {
					underline = true
				}
			},
			java = {
				class = {
					underline = true
				},
				interface = {
					underline = true
				},
				method = {
					fore = "#fc4120"
				}
			},
			jovial = {
				subroutine = {
					fore = "#fc4120"
				},
				type = {
					underline = true
				}
			},
			pascal = {
				routine = {
					fore = "#fc4120"
				},
				type = {
					underline = true
				}
			},
			python = {
				class = {
					underline = true
				},
				["function"] = {
					fore = "#fc4120"
				}
			},
			vhdl = {
				process = {
					fore = "#ffaa00"
				},
				subprogram = {
					fore = "#ffaa00"
				},
				type = {
					underline = true
				}
			}
		}
	}
}
