-- Do Not Edit This File.
-- [32] = default; [33] = line number; [34] = brace highlight; [35] = unmatched brace
return {
	common = {
		style = {
			caret = {
				back = "#1d1d1d"
			},
			comment = {
				fore = "#00bf00",
				italic = true
			},
			deadcode = {
				back = "#606064"
			},
			["doc-comment"] = {
				fore = "#993300",
				italic = true
			},
			["doc-keyword"] = {
				bold = true,
				fore = "#663300",
				italic = true
			},
			["double-quoted-string"] = {
				fore = "#dbc900"
			},
			error = {
				back = "#ff0000",
				eolfilled = true,
				fore = "#ffff00"
			},
			find = {
				back = "#ffff7f"
			},
			["fold-margin"] = {
				back = "#262626"
			},
			identifier = {

			},
			inactive = {
				back = "#1f0000",
				eolfilled = true
			},
			keyword = {
				bold = true,
				fore = "#ff0000"
			},
			label = {
				fore = "#800000"
			},
			number = {
				fore = "#00d0d0"
			},
			operator = {
				bold = true
			},
			preprocessor = {
				bold = true,
				fore = "#008000"
			},
			ref = {
				back = "#55ffff"
			},
			selection = {
				back = "#4d4d4d"
			},
			["single-quoted-string"] = {
				fore = "#dbc900"
			},
			["unclosed-double-quoted-string"] = {
				back = "#1f0000",
				eolfilled = true
			},
			["unclosed-single-quoted-string"] = {
				back = "#1f0000",
				eolfilled = true
			},
			whitespace = {
				fore = "#808080"
			}
		}
	},
	style = {
		[32] = {
			back = "#000000",
			fore = "#ffffff"
		},
		[33] = {
			back = "#a0a0a0"
		},
		[34] = {
			back = "#009000",
			bold = true
		},
		[35] = {
			back = "#bc0000",
			bold = true
		}
	},
	udb = {
		style = {
			ada = {
				["global-variable"] = {
					bold = true,
					fore = "#ff557f",
					underline = true
				},
				["local-variable"] = {
					fore = "#ff557f",
					italic = true
				},
				package = {
					fore = "#ff5500"
				},
				subprogram = {
					fore = "#ff007f"
				}
			},
			cs = {
				class = {
					fore = "#ff5500"
				},
				method = {
					fore = "#ff007f"
				}
			},
			cxx = {
				class = {
					fore = "#ff5500"
				},
				["function"] = {
					fore = "#ff007f"
				},
				["global-variable"] = {
					bold = true,
					fore = "#ff557f",
					underline = true
				},
				["local-variable"] = {
					fore = "#ff557f",
					italic = true
				}
			},
			fortran = {
				subprogram = {
					fore = "#ff007f"
				}
			},
			java = {
				class = {
					fore = "#ff5500"
				},
				method = {
					fore = "#ff007f"
				}
			},
			jovial = {
				subroutine = {
					fore = "#ff007f"
				}
			},
			pascal = {
				routine = {
					fore = "#ff007f"
				}
			},
			python = {
				class = {
					fore = "#ff5500"
				},
				["function"] = {
					fore = "#ff007f"
				}
			},
			vhdl = {
				subprogram = {
					fore = "#ff007f"
				}
			}
		}
	}
}
