-- Do Not Edit This File.
-- [32] = default; [33] = line number; [34] = brace highlight; [35] = unmatched brace
return {
  common = {
    style = {
      caret = {
        back = "#e9e9e9"
      },
      comment = {
        fore = "#0000ff",
        italic = true
      },
      deadcode = {
        back = "#C0C0C0"
      },
      ["doc-comment"] = {
        fore = "#993300",
        italic = true
      },
      ["doc-keyword"] = {
        bold = true,
        fore = "#663300",
        italic = true
      },
      ["double-quoted-string"] = {
        fore = "#cc0000"
      },
      error = {
        back = "#ff0000",
        eolfilled = true,
        fore = "#ffff00"
      },
      find = {
        back = "#ff0000"
      },
      ["fold-margin"] = {
        back = "#c0c0c0"
      },
      identifier = {

      },
      inactive = {
        back = "#ffdddd",
        eolfilled = true
      },
      keyword = {
        bold = true,
        fore = "#000080"
      },
      label = {
        fore = "#800000"
      },
      number = {
        fore = "#008080"
      },
      operator = {
        bold = true
      },
      preprocessor = {
        bold = true,
        fore = "#008000"
      },
      ref = {
        back = "#00ff00"
      },
      selection = {
        back = "#ccccff",
        eolfilled = true
      },
      ["single-quoted-string"] = {
        fore = "#800080"
      },
      ["unclosed-double-quoted-string"] = {
        back = "#e0c0e0",
        eolfilled = true
      },
      ["unclosed-single-quoted-string"] = {
        back = "#e0c0e0",
        eolfilled = true
      },
      whitespace = {
        fore = "#808080"
      }
    }
  },
  style = {
    [32] = {
      back = "#ffffff",
      fore = "#000000"
    },
    [33] = {
      back = "#a0a0a0"
    },
    [34] = {
      back = "#00ff00",
      bold = true
    },
    [35] = {
      back = "#ff0000",
      bold = true
    }
  },
  udb = {
    style = {
      ada = {
        ["global-variable"] = {
          bold = true,
          fore = "#003366"
        },
        ["local-variable"] = {
          fore = "#003366",
          italic = true
        },
        subprogram = {
          fore = "#800000"
        },
        type = {
          underline = true
        }
      },
      cs = {
        class = {
          underline = true
        },
        enumerator = {
          fore = "#0080ff"
        },
        method = {
          fore = "#800000"
        },
        type = {
          underline = true
        }
      },
      cxx = {
        class = {
          underline = true
        },
        enumerator = {
          fore = "#0080ff"
        },
        ["function"] = {
          fore = "#800000"
        },
        ["global-variable"] = {
          bold = true,
          fore = "#003366"
        },
        ["local-variable"] = {
          fore = "#003366"
        },
        macro = {
          bold = true,
          fore = "#800080"
        },
        ["member-function"] = {
          fore = "#800000",
          italic = true
        },
        ["member-variable"] = {
          fore = "#003366",
          italic = true
        },
        parameter = {
          fore = "#004d66"
        },
        type = {
          underline = true
        },
        ["virtual-function"] = {
          bold = true,
          fore = "#800000",
          italic = true
        }
      },
      fortran = {
        subprogram = {
          fore = "#800000"
        },
        type = {
          underline = true
        }
      },
      java = {
        class = {
          underline = true
        },
        interface = {
          underline = true
        },
        method = {
          fore = "#800000"
        }
      },
      jovial = {
        subroutine = {
          fore = "#800000"
        },
        type = {
          underline = true
        }
      },
      pascal = {
        routine = {
          fore = "#800000"
        },
        type = {
          underline = true
        }
      },
      python = {
        class = {
          underline = true
        },
        functionx = {
          fore = "#800000"
        }
      },
      vhdl = {
        process = {
          fore = "#800000"
        },
        subprogram = {
          fore = "#800000"
        },
        type = {
          underline = true
        }
      }
    }
  }
}
